### ISSUE TITLE
Make sure there are no null objects returned from backend

### ISSUE THREAD

**Issue by KucherenkoSerhiy** [mobtimeapp/mobtime#287]
**Why**: A parallel user interaction may block a room (forever). Here is an example:

Assume 2 persons in the same room with some goals. Then, the following happens:

- User 1 **starts** dragging one of the goals
- User 2 removes the goal
- User 1 **finishes** his operation by dropping a goal

At this point, the room is blocked: once any user enters it, the buttons do not react to clicks, as the following console error appears:

Uncaught TypeError: Cannot read properties of null (reading 'completed')
    at index.js:19:41
    at Array.filter (<anonymous>)
    at getGoalsDetails (index.js:19:27)
    at tabs (index.js:70:20)
    at view (timer.js:77:13)
    at render (index.js?module=1:393:10)
    

The error is caused because the  "GET wss://mobti.me/room" call returns a null goal alongside others:
{
  "type": "goals:update",
  "goals": [
    {
      "id": "...",
      "text": "...",
      "completed": true
    },
    **null**,
    {
      "id": "...",
      "text": "...",
      "completed": false
    }
  ]
}

**Comment by mrozbarry** [comment]
What is better when dropping an item:

1. it disappears
2. It reappears
3. The drop is invalidated (similar to 1 but the dragging user gets notified)

**Comment by KucherenkoSerhiy** [comment]
@mrozbarry IMO option 2 (it reappears) is better, as it is much easier to click a button to delete than to write the whole thing again.
